### PR TITLE
Fix usage with objects that have null prototype

### LINKED ISSUE #5: Does not work with objects with no prototype
Objects created with `Object.create(null)` do not work well with this package. The reason is that this packages uses `hasOwnProperty` which is not available in these cases.

Changing to `Object.protototype.hasOwnProperty.call(obj, prop)` should work. Alternatively you may use lodash `has`.

### PR DESCRIPTION
**Pull request by satazor**
Closes #5 

I've fixed some inconsistencies I found in the test files, let me know if these changes are ok or if you want them reverted.

### CODE REVIEW

**Review by kibertoad — APPROVED** [review]

**Comment by satazor** [comment]
Fixed the linting error

**Comment by kibertoad** [comment]
thanks a lot!

**Comment by kibertoad** [comment]
Released in 1.2.0

**Comment by satazor** [comment]
No need to say thanks. I'm the one thankful for your module. Btw, love knex :)

**Comment by kibertoad** [comment]
haha, thanks!

**Pull request merged**
